[package]
name = "utils"
version = "0.1.0"
edition = "2024"

[dependencies]
types = { workspace = true }
bs58 = "0.5.1"
yellowstone-grpc-proto = { version = "4.0.0", default-features = false, features = ["plugin"] }