[package]
name = "parser-pumpfun"
version = "0.1.0"
edition = "2024"

[dependencies]
parser-core = { workspace = true }
types = { workspace = true }
utils = { workspace = true }
bs58 = { version = "0.5.1", features = ["check"] }